FROM alpine:latest
RUN apk add --no-cache openjdk8
RUN apk add --no-cache inotify-tools
WORKDIR /opt/appdynamics/machine-agent
COPY --from=dtr.corp.appdynamics.com/appdynamics/machine-agent:latest /opt/appdynamics/machine-agent .
RUN chmod -R 755 /opt/appdynamics/machine-agent
COPY target/FileWatcher-*.zip monitors/FileWatcher.zip
RUN unzip -q monitors/FileWatcher.zip -d monitors/ && \
    rm monitors/FileWatcher.zip
COPY src/integration-test/resources/conf/config.yml monitors/FileWatcher/config.yml
# enable debug logging
RUN sed -i '1,/sigar/ s/info/debug/' conf/logging/log4j.xml
# Setup JAVA_HOME
ENV JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk
ENV PATH="$JAVA_HOME/bin:${PATH}"
CMD ["sh", "-c", "java ${MACHINE_AGENT_PROPERTIES} -jar machineagent.jar"]